### ISSUE TITLE
Worker kill on style recompile

### ISSUE THREAD

**Issue by vojtatom** [MetacitySuite/Metacity#9]
```
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
   self._target(*self._args, **self._kwargs)
 File "/home/monika/metaworkspace/env/lib/python3.8/site-packages/metaworkspace/runtime/processing/runners.py", line 23, in JobWorker
    job = load_job(job_dir)
  File "/home/monika/metaworkspace/env/lib/python3.8/site-packages/metaworkspace/runtime/processing/loader.py", line 35, in load_job
    with open(jobfile, 'r') as job_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/monika/metaworkspace/workspace/jobs/55067c4f-195d-4b23-bea4-9d726780f86e/job.json'
```

Probably race condition between file writes/reads

**Comment by vojtatom** [comment]
Workspace issue, not related to this repo, closing.
